"""add comfort filters to properties

Revision ID: 73a4f4e0a099
Revises: 976296d5cca9
Create Date: 2025-12-16 16:04:51.224507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73a4f4e0a099'
down_revision: Union[str, Sequence[str], None] = '976296d5cca9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('building_type', sa.String(length=50), nullable=True))
    op.add_column('properties', sa.Column('heating_type', sa.String(length=50), nullable=True))
    op.add_column('properties', sa.Column('has_air_conditioning', sa.Boolean(), nullable=True))
    op.add_column('properties', sa.Column('parking_type', sa.String(length=50), nullable=True))
    op.add_column('properties', sa.Column('has_balcony', sa.Boolean(), nullable=True))
    op.add_column('properties', sa.Column('pets_allowed', sa.Boolean(), nullable=True))
    op.add_column('properties', sa.Column('furnished', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'furnished')
    op.drop_column('properties', 'pets_allowed')
    op.drop_column('properties', 'has_balcony')
    op.drop_column('properties', 'parking_type')
    op.drop_column('properties', 'has_air_conditioning')
    op.drop_column('properties', 'heating_type')
    op.drop_column('properties', 'building_type')
    # ### end Alembic commands ###
