"""extend properties filters

Revision ID: 976296d5cca9
Revises: 0483d9f39bcd
Create Date: 2025-12-15 16:37:11.915011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '976296d5cca9'
down_revision: Union[str, Sequence[str], None] = '0483d9f39bcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('transaction_type', sa.String(length=20), nullable=True))
    op.add_column('properties', sa.Column('district', sa.String(length=120), nullable=True))
    op.add_column('properties', sa.Column('street', sa.String(length=180), nullable=True))
    op.add_column('properties', sa.Column('currency', sa.String(length=10), nullable=True))
    op.add_column('properties', sa.Column('area_sqm', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('rooms', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('bedrooms', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('bathrooms', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('floor', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('total_floors', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('not_first_floor', sa.Boolean(), nullable=True))
    op.add_column('properties', sa.Column('condition', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'condition')
    op.drop_column('properties', 'not_first_floor')
    op.drop_column('properties', 'total_floors')
    op.drop_column('properties', 'floor')
    op.drop_column('properties', 'bathrooms')
    op.drop_column('properties', 'bedrooms')
    op.drop_column('properties', 'rooms')
    op.drop_column('properties', 'area_sqm')
    op.drop_column('properties', 'currency')
    op.drop_column('properties', 'street')
    op.drop_column('properties', 'district')
    op.drop_column('properties', 'transaction_type')
    # ### end Alembic commands ###
